### ISSUE TITLE
Outdated as of this post

### ISSUE THREAD

**Issue by m12Z61** [NightmareXIV/EnmityHp#7]
As per the title, is there any intention of updating it in the future, or am I using the wrong one? I might be out of the loop here, so apologies in advance.

![outdated](https://user-images.githubusercontent.com/110716308/197223246-59488376-d96a-4826-a0c7-9f123e1105c3.png)

**Comment by Limiana** [comment]
Hello, you have old version stuck, please press trashcan icon to delete it and install once again

**Comment by m12Z61** [comment]
I got it working now, never considered it to be the case but thanks for helping regardless! Cheers.
